### ISSUE TITLE
DAGNABBIT Error Pauses Bot

### ISSUE THREAD

**Issue by Oalecj** [zumicts/QuizzerUp#4]
Sometimes, people's connection unintentionally/intentionally drops out, and you get a DAGNABBIT: The opponent's connection has timed out (or something like that). QuizzerUP does not click "back" for you, meaning the bot is paused until you find out and manually fix it. I may be able to provide a screenshot if it happens again. Thanks for the very useful tool!
- Oalecj

**Comment by zumicts** [comment]
Thanks for the headsup!  I'll see if for this weekend I can fix this.

**Comment by Oalecj** [comment]
Oh, also this only happens during matchmaking. If it happens during a match it's fine.

**Comment by haroldma-zz** [comment]
This issue is no longer a problem with the latest v3.0 update of QuizzerUp.
